FROM tomcat:9.0
RUN apt-get -y update && \
    apt-get -y install default-jdk maven git
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git && \
    cd boxfuse-sample-java-war-hello && \
    JAVA_HOME=/usr/lib/jvm/default-java/ mvn package
RUN cp boxfuse-sample-java-war-hello/target/hello-*.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
