FROM ubuntu:18.04
RUN apt-get -y update && \
    apt-get -y install python-all python-pip p7zip-full
WORKDIR /opt/webapp
COPY webapp.7z /opt/webapp
RUN 7z e webapp.7z
RUN pip install -qr requirments.txt
EXPOSE 8080
CMD ["python", "app.py"]
